name: todo_app
description: "Todo Application"
#flutter: 3.38.5
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
  #   - images/a_dot_ham.jpeg


  fonts:
    - family: IBMPlexMonoRegular
      fonts:
        - asset: IBMPlexMono-Regular.ttf
    - family: IBMPlexMonoMedium
      fonts:
        - asset: assets/fonts/IBMPlexMono-Medium.ttf
    - family: IBMPlexMonoSemiBold
      fonts:
        - asset: assets/fonts/IBMPlexMono-SemiBold.ttf
    - family: IBMPlexMonoBold
      fonts:
        - asset: assets/fonts/IBMPlexMono-Bold.ttf
